# Generated by Django 4.1.7 on 2023-03-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0005_alter_category_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSearch',
        ),
    ]
